.PHONY: clean All

All:
	@echo "----------Building project:[ projec1 - Debug ]----------"
	@cd "projec1" && "$(MAKE)" -f  "projec1.mk"
clean:
	@echo "----------Cleaning project:[ projec1 - Debug ]----------"
	@cd "projec1" && "$(MAKE)" -f  "projec1.mk" clean
