.PHONY: clean All

All:
	@echo "----------Building project:[ project_1 - Debug ]----------"
	@cd "project_1" && "$(MAKE)" -f  "project_1.mk"
clean:
	@echo "----------Cleaning project:[ project_1 - Debug ]----------"
	@cd "project_1" && "$(MAKE)" -f  "project_1.mk" clean
