.PHONY: clean All

All:
	@echo "----------Building project:[ helloWorld - Debug ]----------"
	@cd "helloWorld" && "$(MAKE)" -f  "helloWorld.mk"
clean:
	@echo "----------Cleaning project:[ helloWorld - Debug ]----------"
	@cd "helloWorld" && "$(MAKE)" -f  "helloWorld.mk" clean
